services:
  - type: web
    name: escrower-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: LOG_GROUP_ID
        sync: false
      - key: UPI_ID
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: RENDER_URL
        sync: false
      - key: PORT
        value: "8080"
      - key: TG_API_ID
        sync: false
      - key: TG_API_HASH
        sync: false
      - key: TELETHON_SESSION
        sync: false
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
      - key: ESCROW_FEE
        value: "2.5"
      - key: BOT_NAME
        value: "OTC Escrow By PAGAL Bot"
    healthCheckPath: /health
    autoDeploy: true
